List wordsList = [
  ["The one who rules", "King"],
  ["Something without purpose", "Aimless"],
  ["Someone who shows courage", "brave"],
  ["Someone clever or smart", "Brilliant"],
  ["Something infinite", "BOUNDLESS"],
  ["Something bitter", "acrid"],
  ["Something very dearly", "beloved"],
  ["Something washed or dirt free", "clean"],
  ["Far below from the surface", "deep"],
  ["A vertical position", "erect"],
  ["A desired effect", "efficient"],
  ["Something without end", "endless"],
  ["Something fast moving", "quick"],
  ["Something kept alone", "isolated"],
  ["To achieve or complete successfully", "Accomplish"],
  ["To increase in sound", "amplify"],
  ["To make changes", "Alter"],
  ["To squeeze together", "compress"],
  ["To bring to an end", "conclude"],
  ["To a great degree", "immensely"],
  ["Very eager or intense", "keen"],
  ["A unit of time", "minutes"],
];

List<String> alphabets = [
  "Q",
  "W",
  "E",
  "R",
  "T",
  "Y",
  "U",
  "A",
  "S",
  "D",
  "F",
  "G",
  "H",
  "J",
  "Z",
  "X",
  "C",
  "V",
  "B",
  "N",
  "M",
  "I",
  "O",
  "P",
  "K",
  "L",
];
